# This is a basic workflow to help you get started with Actions

name: Update POT source

# Controls when the workflow will run
on:
  # Run this script everyday.
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Fetching the latest Blender pot file
      - name: Start fetching
        run: bash update.sh

      # Push back to zh_TW
      - name: Push to zh_TW
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'blender.pot: update - ${date}'
